# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import models_database_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_type', models.CharField(choices=[('STR', 'Short String'), ('NUM', 'Numeric'), ('DATE', 'Date'), ('TEXT', 'Long Text'), ('MD', 'Markdown Text'), ('FILE', 'File')], default='TEXT', max_length=50)),
                ('sort_order', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_database_app.Attribute')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='models_database_app.Model')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAttributeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('string_value', models.CharField(blank=True, max_length=500)),
                ('text_value', models.TextField(blank=True)),
                ('markdown_value', models.TextField(blank=True)),
                ('markdown_value_html', models.TextField(blank=True, default='', editable=False)),
                ('date_value', models.DateField(null=True)),
                ('number_value', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('file_value', models.FileField(blank=True, upload_to=models_database_app.models.ModelAttributeRecord.upload_path)),
                ('model_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='models_database_app.ModelAttribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='models_database_app.Model')),
            ],
        ),
        migrations.CreateModel(
            name='VersionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_database_app.Attribute')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='models_database_app.Version')),
            ],
        ),
        migrations.CreateModel(
            name='VersionAttributeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('string_value', models.CharField(blank=True, max_length=500)),
                ('text_value', models.TextField(blank=True)),
                ('markdown_value', models.TextField(blank=True)),
                ('markdown_value_html', models.TextField(blank=True, default='', editable=False)),
                ('date_value', models.DateField(null=True)),
                ('number_value', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('file_value', models.FileField(blank=True, upload_to=models_database_app.models.VersionAttributeRecord.upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='models_database_app.VersionAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='models_database_app.Owner'),
        ),
    ]
