# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0002_auto_20160716_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelattribute',
            name='valid_record_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='versionattribute',
            name='valid_record_id',
            field=models.IntegerField(default=0),
        ),
    ]
