# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0003_auto_20160716_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
