# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0005_attribute_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelattribute',
            options={'ordering': ['attribute__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='modelattributerecord',
            options={'ordering': ['-record_id']},
        ),
        migrations.AlterModelOptions(
            name='versionattribute',
            options={'ordering': ['attribute__sort_order']},
        ),
        migrations.AlterField(
            model_name='modelattributerecord',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelattributerecord',
            name='number_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
    ]
