# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0006_auto_20160717_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='versionattributerecord',
            options={'ordering': ['-record_id']},
        ),
    ]
