# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0008_auto_20160805_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
