# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0009_attribute_allow_multiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('STR', 'Short String'), ('NUM', 'Numeric'), ('DATE', 'Date'), ('TEXT', 'Long Text'), ('MD', 'Markdown Text'), ('FILE', 'File'), ('MULT_CHOICE', 'Multiple Choice')], default='TEXT', max_length=50),
        ),
        migrations.AddField(
            model_name='attributechoice',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='models_database_app.Attribute'),
        ),
    ]
