# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0010_auto_20160807_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAttributeRecordChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_database_app.AttributeChoice')),
                ('model_attribute_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='models_database_app.ModelAttributeRecord')),
            ],
        ),
    ]
