# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_database_app', '0013_attributerequired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributerequired',
            options={'ordering': ['attribute__sort_order']},
        ),
        migrations.AlterField(
            model_name='model',
            name='risk_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='models_database_app.RiskType'),
            preserve_default=False,
        ),
    ]
